version: "3.6"
services:

 mariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=leomariadb

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb

 mailhog:
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025
    depends_on: 
    - mariadb

 leoweb:
   build: .
   ports:
    - 8081:80
   volumes:
    -./:/var/www/html